include = ["*.md", "**/*.md"]
exclude = [
  "target/**",
  "**/node_modules/**",
  "website/src/sample.md",
  "website/src/sample-short.md",
]

[heading]
sentence_case = true
proper_nouns = [
  "Hong Minhee",
  "Hongdown",
  "mise",
  "Windows Package Manager",
]

[code_block.formatters]
javascript = ["deno", "fmt", "--ext=js", "-"]
json = ["deno", "fmt", "--ext=jsonc", "-"]
jsonc = ["deno", "fmt", "--ext=jsonc", "-"]
typescript = ["deno", "fmt", "--ext=ts", "-"]
